image: docker:git

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  CONTAINER_REGISTRY: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2
  # See https://about.gitlab.com/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_TLS_CERTDIR: ''

services:
  - docker:dind


before_script:
  - apk update
  - apk add helm --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted


stages:
- test
- release

lint:
  stage: test
  script:
  - helm lint ./mgmt

build:
  stage: release
  script:
  - helm package ./mgmt
  artifacts:
    paths:
    - mgmt*.tgz
    expire_in: 7d

dev_build:
  stage: release
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CONTAINER_REGISTRY}
    # - docker pull ${CONTAINER_REGISTRY}/sr_main:latest || true
    - cd ../dev-image && docker build -t ${CONTAINER_REGISTRY}/dev-image:latest .
    - docker tag ${CONTAINER_REGISTRY}/dev-image:latest ${CONTAINER_REGISTRY}/dev-image:$CI_COMMIT_SHA
    - docker push ${CONTAINER_REGISTRY}/dev-image:$CI_COMMIT_SHA
    - docker push ${CONTAINER_REGISTRY}/dev-image:latest
