default:
  image: debian

before_script:
  - curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https --yes
  - echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
  - sudo apt-get update
  - sudo apt-get install helm


stages:
- test
- release

lint:
  stage: test
  script:
  - helm lint ./nagios

build:
  stage: release
  script:
  - helm init --client-only
  - helm package ./nagios
  artifacts:
    paths:
    - mgmt*.tgz
    expire_in: 7d
