image: docker:git

before_script:
  - apk update
  - apk add helm


stages:
- test
- release

lint:
  stage: test
  script:
  - helm lint ./mgmt

build:
  stage: release
  script:
  - helm package ./mgmt
  artifacts:
    paths:
    - mgmt*.tgz
    expire_in: 7d

dev_build:
  stage: release
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CONTAINER_REGISTRY}
    # - docker pull ${CONTAINER_REGISTRY}/sr_main:latest || true
    - cd ../dev-image && docker build -t ${CONTAINER_REGISTRY}/dev-image:latest .
    - docker tag ${CONTAINER_REGISTRY}/dev-image:latest ${CONTAINER_REGISTRY}/dev-image:$CI_COMMIT_SHA
    - docker push ${CONTAINER_REGISTRY}/dev-image:$CI_COMMIT_SHA
    - docker push ${CONTAINER_REGISTRY}/dev-image:latest
