image: debian

before_script:
  - apt update
  - apt install -y curl gnupg
  - curl https://baltocdn.com/helm/signing.asc | apt-key add -
  - apt-get install -y apt-transport-https --yes
  - echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
  - apt-get update
  - apt-get install -y helm


stages:
- test
- release

lint:
  stage: test
  script:
  - helm lint ./mgmt

build:
  stage: release
  script:
  - helm package ./mgmt
  artifacts:
    paths:
    - mgmt*.tgz
    expire_in: 7d

dev_build:
  stage: release
  script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CONTAINER_REGISTRY}
    # - docker pull ${CONTAINER_REGISTRY}/sr_main:latest || true
    - cd ../dev-image && docker build -t ${CONTAINER_REGISTRY}/dev-image:latest .
    - docker tag ${CONTAINER_REGISTRY}/dev-image:latest ${CONTAINER_REGISTRY}/dev-image:$CI_COMMIT_SHA
    - docker push ${CONTAINER_REGISTRY}/dev-image:$CI_COMMIT_SHA
    - docker push ${CONTAINER_REGISTRY}/dev-image:latest
