[vmware]
pop-dev ansible_host=192.168.244.128 ansible_user=monofuel

[farmlife]
farmlifenas ansible_host=192.168.13.186 ansible_user=root
farmlifepi ansible_host=192.168.13.108 ansible_user=pi

[proxmox]
mjolnir ansible_host=192.168.11.234 ansible_user=root
king ansible_host=192.168.11.152 ansible_user=root