FROM linuxserver/code-server

# TODO use github.com/monofuel/monoboot scripts

# TODO change default username
# TODO change default shell

# Setup dev environment
RUN apt update
RUN apt install -y ansible build-essential python-pip nmap tmux vim
