apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "media.fullname" . }}
  labels:
    {{- include "media.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "media.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "media.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "media.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: plex
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: TZ
            value: America/Los_Angeles
          - name: PLEX_UID
            value: '1002'
          - name: PLEX_GID
            value: '1002'
          - name: HOSTNAME
            value: Mjolnir
          - name: ADVERTISE_IP
            value: http://157.131.99.30:32400
          ports:
            - name: http
              containerPort: 32400
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 32400
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 32400
          volumeMounts:
          - name: plex-config-storage
            mountPath: /config
          - name: plex-transcode-storage
            mountPath: /transcode
          - name: plex-data-movie-storage
            mountPath: /media/movies
          - name: plex-data-tv-storage
            mountPath: /media/tv
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: radarr
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "linuxserver/radarr:latest"
          imagePullPolicy:  {{ .Values.image.pullPolicy }}
          env:
          - name: TZ
            value: America/Los_Angeles
          - name: PUID
            value: '1002'
          - name: PGID
            value: '1002'
          ports:
            - name: radarr
              containerPort: 7878
              protocol: TCP
          volumeMounts:
          - name: plex-data-movie-storage
            mountPath: /media/movies
          - name: radarr-storage
            mountPath: /config
          - name: downloads-storage
            mountPath: /downloads
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: sabnzbd
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "sabnzbd/sabnzbd:latest"
          imagePullPolicy:  {{ .Values.image.pullPolicy }}
          env:
          - name: TZ
            value: America/Los_Angeles
          - name: SABNZBD_UID
            value: '1002'
          - name: SABNZBD_GID
            value: '1002'
          ports:
            - name: sabnzbd
              containerPort: 8080
              protocol: TCP
          volumeMounts:
          - name: plex-data-movie-storage
            mountPath: /media/movies
          - name: plex-data-tv-storage
            mountPath: /media/tv
          - name: sabnzbd-storage
            mountPath: /datadir
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: plex-config-storage
        nfs:
          server: 192.168.11.126
          path: /mnt/Crystarium/home/plex/config
      - name: plex-transcode-storage
        nfs:
          server: 192.168.11.126
          path: /mnt/Crystarium/home/plex/transcode
      - name: plex-data-movie-storage
        nfs:
          server: 192.168.11.126
          path: /mnt/Crystarium/media/movies
      - name: plex-data-tv-storage
        nfs:
          server: 192.168.11.126
          path: /mnt/Crystarium/media/tv
      - name: sabnzbd-storage
        nfs:
          server: 192.168.11.126
          path: /mnt/Crystarium/home/plex/sabnzbd
      - name: radarr-storage
        nfs:
          server: 192.168.11.126
          path: /mnt/Crystarium/home/plex/radarr
      - name: downloads-storage
        nfs:
          server: 192.168.11.126
          path: /mnt/Crystarium/media/downloads