apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-config-volume
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce 
  capacity:
    storage: 50Gi
  hostPath:
    path: /host/dev/config