apiVersion: v1
kind: Service
metadata:
  name: {{ include "dev.fullname" . }}
  labels:
    {{- include "dev.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "dev.selectorLabels" . | nindent 4 }}
