apiVersion: v1
kind: Service
metadata:
  name: {{ include "nagios.fullname" . }}-home-assistant
  labels:
    {{- include "nagios.labels" . | nindent 4 }}
spec:
  type: {{ .Values.homeAssistant_service.type }}
  ports:
    - port: {{ .Values.homeAssistant_service.port }}
      nodePort: {{ .Values.homeAssistant_service.nodePort }}
      protocol: TCP
      name: home-assistant
  selector:
    {{- include "nagios.selectorLabels" . | nindent 4 }}
